# Pase editorial del PCR: Figura 4 como tabla, II.3 y IV a la mitad con tablas, cuadro de sensibilidad
import re
import passlib as L
from passlib import full,pairs,cell_set,delete_para,rebuild_table,add_rows,new_p_from,new_table,table_template,insert_after,insert_before,gen_pass,words
AUT='Revisión 2026-10 – versión final'
A=L.init('salida_om/PCR_EC-L1147 (con control de cambios).docx',AUT)
w_ii3_antes=words(1151,1178); w_iv_antes=words(1353,1403); w_iv_prosa_antes=words(1397,1403)
TPL=table_template('Tabla 3 Síntesis integral del contrafactual')
def tab(rows,widths): return new_table(TPL,rows,widths)
def title(text): return new_p_from(1038,text)
def note(text): return new_p_from(413,text)
def body(text): return new_p_from(1153,text)
# ====================== FIGURA 4 → TABLA ======================
L.delete_drawing_near(441)
full(441,'Tabla 1A Lógica vertical del Programa verificada al cierre (2023)')
pairs(442,[('de esta figura','de esta tabla')],strict=False)
LV=[['Nivel','Componente I: expansión y reforzamiento del SND','Componente II: eficiencia y fiabilidad de la red','Componente III: fortalecimiento institucional'],
 ['Objetivo general de desarrollo','Dar continuidad al reforzamiento del Sistema Nacional de Distribución (SND), facilitando la transformación de la matriz energética y la provisión de un servicio eléctrico de calidad','ídem','ídem'],
 ['Impactos','I.1 Mitigación del cambio climático: emisiones de CO₂ anuales disminuidas por desplazamiento de GLP por electricidad (kt CO₂eq/año)','I.2 Eficiencia y sostenibilidad: nivel de pérdidas eléctricas disminuidas en empresas intervenidas (%); costo económico evitado por interrupciones y restricciones de capacidad (USD/año); valor económico de la energía recuperada (USD/año)','Aporte transversal de eficiencia: personal capacitado que mejora el desempeño de todos los componentes'],
 ['Resultados (objetivos específicos de desarrollo)','OED I. Apoyar el reforzamiento de la infraestructura eléctrica en el SND. R1.1 Potencia instalada en S/E del SND (MVA); R1.2 potencia instalada en transformadores de distribución (MVA); R1.3 energía no suministrada evitada por ampliación de capacidad (GWh/año)','OED II. Contribuir a la modernización y eficiencia en la gestión de la demanda: R2.1 energía recuperada por pérdidas técnicas (GWh/año); R2.2 energía recuperada por pérdidas no técnicas (GWh/año). OED III. Mejorar la confiabilidad del servicio: R3.1 FMIk (veces/año); R3.2 TTIk (horas/año); R3.3 energía no suministrada evitada por mejora de confiabilidad (GWh/año)','—'],
 ['Productos','PC1.1 Proyectos de subtransmisión ejecutados; PC1.2 proyectos de distribución ejecutados; PC1.3 proyectos de fiscalización contratados','PC2.1 Dispositivos inteligentes en alimentadores primarios (reconectadores y reguladores); PC2.2 automatización y adecuación de subestaciones; PC2.3 medición inteligente en transformadores, alimentadores y consumidores incidentes; PC2.4 centros de datos y de control; PC2.5 supervisión y fiscalización','PC3.1 Estrategia de capacitación; PC3.2 apoyo a la implementación de la estrategia'],
 ['Aporte al cálculo de los resultados','Del R1.1 al R2.1','Del R2.2 al R3.3','Eficiencia transversal']]
insert_after(441,tab(LV,[1700,2800,3400,2240]),text='Tabla 1A Lógica vertical del Programa verificada al cierre (2023)')
# ====================== II.3 EFICIENCIA ======================
full(1153,'El Programa cubre su costo de oportunidad social. Con el gasto de operación y mantenimiento de la medición inteligente al 2,5 % anual de su CAPEX, el valor presente de los costos es de USD 72,55 millones y el de los beneficios de USD 105,65 millones en el resultado publicado (120,27 con la convención de facturación): energía adicional servida por la capacidad nueva (56,74, valorada por el excedente del consumidor), continuidad del servicio (44,26: refuerzo de capacidad más los beneficios de confiabilidad por frecuencia y duración), medición inteligente (2,37 publicado; 16,99 con la convención) y pérdidas de subtransmisión evitadas (2,28). El VAN publicado es de USD 33.101.387,79 al 12 %, con razón beneficio/costo de 1,46, TIR de 18,34 % (6,34 puntos sobre la tasa social) y recuperación descontada en 2027. La Tabla 3A resume el resultado y cruza las dos decisiones de presentación: la convención de la medición inteligente y la inclusión de los beneficios de confiabilidad.')
ROWS_S=[['Caso','VAN al 12 % (USD de 2015)','TIR','Razón beneficio/costo','Recuperación descontada','P(VAN < 0)'],
 ['Resultado publicado, con beneficios de confiabilidad ¹','+33.101.388','18,34 %','1,4563','2027','7,70 %'],
 ['Convención de facturación, con beneficios de confiabilidad ²','+47.725.356','20,22 %','1,6578','2026','no simulada ⁵'],
 ['Resultado publicado, sin beneficios de confiabilidad ³','+115.428','12,02 %','1,0016','2045','54,32 %'],
 ['Convención de facturación, sin beneficios de confiabilidad ⁴','+14.739.396','14,73 %','1,2032','2033','no simulada ⁵']]
NOTAS_S=['Notas: (1) Resultado publicado: la facturación recuperada por la medición inteligente es transferencia y solo cuenta su componente real (f = 1,2; λ = 0,5); incluye los beneficios de confiabilidad por frecuencia (C2.1) y duración (C2.2/C2.4), estimados sobre el panel histórico de calidad de servicio por alimentador del regulador (ARCONEL, 2008-2025). Es la cifra que publica este informe. (2) Convención de facturación: toda la energía recuperada se acredita a la tarifa; se declara y no se publica. (3) y (4) Sin beneficios de confiabilidad: los mismos casos retirando los canales de frecuencia y duración; conservan la energía no suministrada evitada por capacidad. Muestran cuánto del resultado descansa en la confiabilidad. (5) La simulación (10.000 corridas) se corre sobre el resultado publicado y su variante sin confiabilidad; la convención no se simula. En los cuatro casos: 2015-2045, dólares de 2015, 12 %, O&M de la medición inteligente al 2,5 % y VP de costos de USD 72.549.627.',
 'Fuente: Libro de Confiabilidad y VAN (EEO#4), hojas Flujo_Anual (filas 15, 22, 24 y 34; columnas D y E, resultado publicado con y sin beneficios de confiabilidad; B y C, convención de facturación) y MC_B (celdas G4 y G5). Elaboración propia.']
blk=title('Tabla 3A Resultado económico ex post y sensibilidad a las dos decisiones de presentación')+tab(ROWS_S,[3000,1600,1100,1300,1500,1640])+''.join(note(t) for t in NOTAS_S)
L.insert_after_contains('La Tabla 3A resume el resultado y cruza las dos decisiones de presentación',blk)
full(1155,'Regla de publicación. La facturación recuperada por la medición inteligente (C2.3) es una transferencia de los usuarios a la distribuidora y no un beneficio del programa: el resultado publicado cuenta solo la conservación de consumo (f ≈ 1,2), el valor de uso neteado (λ ≈ 0,5) y el ahorro operativo, y resta USD 14.623.967,72 a la convención de facturación del expediente (USD 47.725.355,51), que se declara y no se publica. Los beneficios de confiabilidad —USD 20.415.038,67 por la menor frecuencia de las interrupciones (C2.1) y USD 12.570.921,28 por su menor duración (C2.2 y C2.4)— se valoran por contribución y no por atribución: el estudio de eventos de los reconectadores no identifica el efecto con confianza (Análisis Contrafactual, EEO#2) y el canal se valora por el nivel previo a la obra neto de tendencia, con sus cantidades físicas estimadas sobre el panel histórico de calidad de servicio por alimentador del regulador. Dos resultados quedan en memoria, fuera de este valor: las pérdidas técnicas evitadas por las obras de distribución y el acceso y la regularización de usuarios sin medidor (C1.2 con y sin red), sin dato de conexiones nuevas por obra.')
delete_para(1157)
full(1158,'Por objetivo y por subcomponente (Tabla 3B), el OED I aporta USD 16,20 millones con las dos valoraciones; el OED II, USD 17,52 millones publicados (32,14 con la convención), sostenido por los beneficios de confiabilidad; y el OED III, −0,62 por construcción, porque la capacitación entra solo con su costo. La subtransmisión (C1.1) produce el 61,0 % del valor presente de los beneficios con una razón beneficio/costo de 1,81; la distribución tiene canal propio pero su costo lo supera; y los cinco habilitantes (fiscalización, supervisión, capacitación y fortalecimiento, USD 2,42 millones) no tienen beneficio propio identificado, sin que ninguno revierta el signo del componente que lo recibe: el canal de frecuencia por sí solo cubre ocho veces el costo de todos ellos. Esa ausencia de beneficio acreditado es una limitación de la evidencia, no un juicio sobre su utilidad.')
ROWS_B=[['Ámbito','VP de beneficios (MUS$)','VP de costos (MUS$)','VAN publicado (MUS$)','VAN con la convención de facturación (MUS$)','B/C publicado'],
 ['Programa EC-L1147','105,65','72,55','33,10','47,73','1,46'],
 ['OED I. Infraestructura','70,30','54,10','16,20','16,20','1,30'],
 ['OED II. Modernización, eficiencia y confiabilidad','35,35','17,83','17,52','32,14','1,98'],
 ['OED III. Estrategia de capacitación','0,00','0,62','−0,62','−0,62','0,00'],
 ['C1.1 Subtransmisión','64,40','35,64','28,76','28,76','1,81'],
 ['C1.2 Distribución','5,90','16,72','−10,82','−10,82','0,35'],
 ['C2.1 Dispositivos inteligentes en alimentadores (frecuencia)','20,42','4,17','16,25','16,25','4,90'],
 ['C2.2 Automatización de subestaciones (duración)','12,45','5,90','6,56','6,56','2,11'],
 ['C2.3 Medición inteligente','2,37 (16,99 con la convención)','4,60','−2,23','12,39','0,51 (3,70)'],
 ['C2.4 Centros de datos y de control (duración)','0,12','3,11','−3,00','−3,00','0,04'],
 ['Habilitantes C1.3, C2.5, C3.1 y C3.2','0,00','2,42','−2,42','−2,42','0,00']]
blk=title('Tabla 3B Resultado económico por objetivo específico y por subcomponente (valor presente al 12 %, millones de USD de 2015)')+tab(ROWS_B,[3300,1500,1300,1400,1700,940])+note('Fuente: Libro de Confiabilidad y VAN (EEO#4), hojas AMI_Regla (B33:D43), VAN_Programa y Mapa_Objetivos; VP de costos con el O&M de la medición inteligente al 2,5 % anual de su CAPEX. Los VAN de los OED suman el total del programa; los beneficios de C2.1, C2.2 y C2.4 son contribución, no atribución. Elaboración propia.')
L.insert_after_contains('el canal de frecuencia por sí solo cubre ocho veces el costo de todos ellos',blk)
full(1159,'Riesgo. La simulación de Montecarlo (10.000 corridas, nueve parámetros inciertos) sitúa la probabilidad de VAN negativo en 7,70 %; sin los beneficios de confiabilidad sube al 54,32 %. Ningún parámetro anula el VAN publicado dentro de su banda de evidencia (Tabla 3C). El riesgo del signo es de precios y costos, no de cantidades: el canal de energía adicional servida (53,7 % de los beneficios) se valora por el excedente sobre la tarifa y supone que la tarifa cubre el costo marginal de suministro, lo que ocurre en un año normal (9,1 frente a 9,2 centavos por kWh) y no en uno de crisis de generación (12,5). El VAN publicado resiste una brecha media de 0,81 centavos por kWh en el horizonte, un año de crisis de cada cuatro. El resultado declara tres fragilidades con su valor de cambio y conserva el signo en los tres escenarios de degradación posterior al cierre.')
ROWS_C=[['Prueba','Resultado sobre el VAN publicado'],
 ['Probabilidad de VAN negativo (hoja MC_B; 10.000 corridas, nueve parámetros)','7,70 % (media 27,75; mediana 26,14; percentiles 5 y 95 en −3,35 y 64,77 MUS$). Sin los beneficios de confiabilidad: 54,32 %; sin el canal de duración: 23,11 %'],
 ['Valores de cambio (ningún parámetro anula el VAN dentro de su banda)','Excedente del consumidor 6,25 % (adoptado 15 %; banda 10-30); utilización de la capacidad nueva 41,66 % (banda 42,78-100); tarifa media 3,57 ¢/kWh (9,2; banda 7-11); energía por capacidad 1,11 GWh/MVA-año (2,67; banda 2,36-3,23); CENS 387 USD/MWh (1.533; banda 789-1.762)'],
 ['Brecha entre costo de suministro y tarifa','Cada centavo por kWh resta 41,1 MUS$ al canal de energía; el VAN publicado resiste una brecha media de 0,81 ¢/kWh (1,16 con la convención): un año de crisis de generación de cada cuatro'],
 ['Fragilidad 1: carbono','Con el costo del CO₂ de la senda baja del Banco Mundial el VAN pasaría a −21,12 MUS$ y la TIR a 5,50 %; el 61 % de esa senda lo anula. El titular va sin carbono'],
 ['Fragilidad 2: costo marginal de los fondos públicos','Aplicado al flujo fiscal del Estado central, el signo se invierte en 1,277, dentro de la banda 1,2-1,3'],
 ['Fragilidad 3: conversión de horas de interrupción a energía no suministrada','Con el factor nacional de 0,4145 el VAN baja a 14,41 MUS$ y la TIR a 14,95 %; sigue positivo'],
 ['Sostenibilidad posterior al cierre (S1 leve, S2 moderada, S3 severa)','+28,40; +17,97; +7,02 MUS$; TIR 17,72 %, 16,13 % y 13,94 %. Conservar el 29,6 % de los beneficios posteriores a 2025 (99,6 % sin los beneficios de confiabilidad)'],
 ['Tasa de descuento','77,7 MUS$ al 8 % y 9,0 al 16 %; la TIR de 18,34 % es el punto de equilibrio']]
blk=title('Tabla 3C Riesgo, valores de cambio, fragilidades declaradas y sostenibilidad del resultado publicado')+tab(ROWS_C,[3300,6840])+note('Fuente: Libro de Confiabilidad y VAN (EEO#4), hojas MC_B, Umbrales_B, Brecha_Tarifaria, Carbono_B, MCPF, CENS_ENS y Sostenibilidad_Tasa. Elaboración propia.')
L.insert_after_contains('y conserva el signo en los tres escenarios de degradación posterior al cierre',blk)
for i in (1160,1162,1164,1165): delete_para(i)
full(1168,'El desempeño operativo fue mixto: las metas físicas se cumplieron y sobrecumplieron, pero el plazo se extendió 49 meses (97 efectivos frente a 48), por restricciones fiscales de contrapartida, licitaciones descentralizadas en 20 distribuidoras y la pandemia. Los ahorros de licitación del Componente I (10 % a 22 %) financiaron obras adicionales sin elevar el techo presupuestario; se ejecutó el 98,46 % del contratado (USD 78,77 millones; 77.637.798,54 de inversión sin impuestos sellados pago a pago). El costo del retraso es pequeño con la regla por componente, que adelanta cada beneficio junto con el activo que lo produce: USD 0,17 millones de valor presente, con una cota superior de 48,1 si todos los beneficios se adelantaran por igual (Análisis Económico, apartado 8.5). La demora desplazó valor hacia el futuro en lugar de destruirlo (Tabla 3D).')
ROWS_D=[['Concepto','Previsto','Efectivo'],
 ['Plazo de ejecución','48 meses (cláusula 2.04 del contrato)','97 meses (extensión acumulada de 49 meses, 102 %)'],
 ['Último desembolso','30 de septiembre de 2019','31 de octubre de 2023'],
 ['Monto ejecutado','USD 80,0 millones contratados','USD 78,77 millones (98,46 %); inversión sin impuestos USD 77.637.798,54'],
 ['Ahorros de licitación (Componente I)','Presupuesto referencial','12,9 % en subtransmisión; 21,5 % en subestaciones automatizadas; 17,8 % en centros de gestión'],
 ['Cumplimiento de las metas físicas','100 %','110 % subtransmisión; 163 % distribución; 151 % fiscalización; 666 % capacitación (1.999 personas frente a 300)'],
 ['Costo del retraso, valor presente','Cierre en 2019','USD 0,17 millones con la regla por componente; cota superior USD 48,1 millones con adelanto uniforme de todos los beneficios'],
 ['Causas del retraso','—','Restricciones fiscales de contrapartida; licitaciones descentralizadas en 20 distribuidoras; pandemia (25 % del retraso)']]
blk=title('Tabla 3D Eficiencia operativa: plazo, ejecución, ahorros de licitación y costo del retraso')+tab(ROWS_D,[2600,2800,4740])+note('Fuente: contrato de préstamo (cláusula 2.04), maestro de ejecución de 280 proyectos, Análisis Económico (EEO#3, apartado 8.5) y Libro de Confiabilidad y VAN (EEO#4), hoja Retraso_B. Elaboración propia.')
L.insert_after_contains('en lugar de destruirlo (Tabla 3D)',blk)
for i in (1170,1171,1173): delete_para(i)
full(1175,'Por transparencia metodológica: el estimador de diferencias en diferencias del efecto sobre el TTIk (−3,68 horas; IC 95 % [−12,90; +5,55]; p = 0,412) no es significativo ni sobrevive a las pruebas de robustez, porque las 20 distribuidoras recibieron obras y no existe grupo de control. La atribución del delta de TTIk se fija en cero; el beneficio de confiabilidad acreditado procede, por contribución, de los canales de frecuencia y duración y de la energía no suministrada evitada por capacidad (Análisis Contrafactual, EEO#2).')
# ====================== IV. HALLAZGOS Y RECOMENDACIONES ======================
T='IV. Hallazgos y recomendaciones'
H={2:('La medición inteligente recupera 44,8 GWh/año (banda 26,4 a 97,1), pero su valor depende de la regla: VAN de USD +12,4 millones con la convención de facturación y de −2,23 millones en el resultado publicado, donde la facturación recuperada es transferencia. El OED II se sostiene en los beneficios de confiabilidad.',
 '(Banco y ejecutor) Condicionar toda inversión futura en medición inteligente a una línea base de consumo por medidor de al menos doce meses y a la integración con el sistema comercial antes de energizar, con un umbral de recuperación comprometido por contrato.'),
 3:('Los medidores AMI expusieron una brecha no anticipada en los sistemas comerciales heredados de las EED: retrasos en la facturación automática y soluciones puente, que evidencian la necesidad de modernizar la gestión comercial a escala nacional.',
 '(Banco) Incluir en los programas sucesores un componente de modernización de los sistemas comerciales de las EED, complementario al AMI, y dimensionar un gemelo digital para CNEL EP como evolución de SCADA y AMI.'),
 5:('La ejecución descentralizada en 20 distribuidoras fue compleja pero permitió priorizar obras según el perfil de cada empresa; los medidores se concentraron en las unidades de mayor pérdida no técnica, focalización que el balance de red valida. Santa Elena y Esmeraldas quedaron fuera.',
 '(Ejecutor) Mantener la ejecución descentralizada y acortar los ciclos de adquisiciones con marcos contractuales estandarizados preaprobados por el BID, capacitación de las áreas de adquisiciones de las EED y tableros de control que anticipen los cuellos de botella en las transferencias del MEF.'),
 6:('El objetivo de género se sobrecumplió (22 % frente a una meta del 10 %, sobre 1.999 personas capacitadas). Se reporta como resultado y no como valor económico, porque no hay medición del efecto de la capacitación sobre la operación de las redes.',
 '(Banco) Mantener metas de género de al menos 20 % en la capacitación y prever desde el diseño la medición de su efecto (rotación y desempeño del personal capacitado); considerar metas en cargos técnicos y gerenciales de las EED.'),
 8:('La extensión de plazo fue de 49 meses (102 % sobre los 48 originales), por restricciones fiscales, licitaciones descentralizadas y la pandemia (25 % del retraso); aun así se ejecutó el 98,46 % del contratado (USD 78,77 millones).',
 '(Banco y MEF) Anticipar la tramitación de avales del MEF con un plan de gestión financiera vinculante y cláusulas de revisión semestral del flujo de caja que activen comisiones MAE-MEF-BID ante desviaciones materiales.'),
 9:('La estructura mixta (USD 50 millones de Capital Ordinario, 30 del Fondo Chino de Cofinanciamiento y 10,6 de aporte local) mantuvo bajo el costo financiero. El saldo no ejecutado fue de USD 1,23 millones (1,54 %).',
 '(Banco) Documentar el blending OC-EC y CH-EC como caso de estudio y mantener la estructura mixta cuando esté disponible.'),
 11:('La degradación posterior al cierre deja el VAN publicado en USD +28,40 millones (leve), +17,97 (moderada) y +7,02 (severa); hay que conservar el 29,6 % de los beneficios posteriores a 2025. La calidad del O&M no es secundaria: la degradación severa reduce el VAN a menos de una cuarta parte.',
 '(Banco, ejecutor y EED) Condicionar el cierre operativo a un plan de O&M posterior al Banco firmado por cada EED, a una revisión tarifaria de la ARCONEL que cubra los costos operativos y a capacitación in situ en los años 5 y 6; distinguir en los reportes la sostenibilidad financiera de la de resultados.'),
 13:('El valor está concentrado: la energía adicional servida explica el 53,7 % de los beneficios (41,9 % la continuidad) y la subtransmisión, el 61,0 %. El resultado publicado declara tres fragilidades con su valor de cambio: carbono, costo marginal de los fondos públicos y conversión de horas de interrupción a energía no suministrada (Tabla 3C).',
 '(Banco) Incorporar al diseño de los sucesores una prueba de concentración: ningún objetivo específico debería depender de un solo canal para más del 60 % de su valor presente sin un plan de medición de ese canal y una línea base levantada antes del primer desembolso.'),
 14:('Las pérdidas no técnicas del perímetro tratado se deterioraron frente a su contrafactual: 12,58 % frente a 8,31 % en 2023 (4,27 puntos; brecha descriptiva, no atribuible) y 5,26 puntos en 2024. Las pérdidas del SND cerraron en 14,82 % frente a una meta de 11,3 %.',
 '(Banco y ARCONEL) Separar en los sucesores las pérdidas técnicas de las no técnicas, con indicadores, líneas base y responsables distintos: la inversión en red no actúa sobre el hurto, y agregarlos impide diagnosticar cuál de los dos canales falló.'),
 15:('El diseño impide la evaluación causal de la calidad del servicio: las 20 distribuidoras recibieron obras y 16 además automatización, sin grupo de control. Las pruebas de robustez no permiten atribuir el efecto y la atribución del delta de TTIk se fijó en cero.',
 '(Banco) Reservar en los programas de cobertura nacional un grupo de comparación explícito, por rezago deliberado o asignación escalonada documentada, y registrar el cronograma real de energización por activo desde el primer desembolso.'),
 16:('La simulación de riesgo (10.000 corridas, nueve parámetros) sitúa la probabilidad de VAN negativo en 7,70 %. La incertidumbre no está en la ejecución sino en la medición de los beneficios: excedente del consumidor, energía no suministrada evitada por MVA y utilización de la capacidad nueva.',
 '(Banco y ejecutor) Financiar dentro del préstamo la medición de los parámetros de los que depende la evaluación (utilización de la capacidad nueva, energía no suministrada evitada por MVA y consumo por medidor antes y después), con presupuesto y entregables anuales.'),
 17:('El 53,7 % de los beneficios es energía adicional servida por la capacidad instalada; el VAN se anula si la energía por MVA cae a 1,11 GWh/MVA-año (2,67 observado) o la utilización a 0,4166. La utilización pico observada es del 51 % (mediana) y creciente.',
 '(EED y ARCONEL) Publicar anualmente la energía servida por MVA de las subestaciones financiadas (no menos de 1,11 GWh/MVA-año, valor de cambio del resultado publicado) y la utilización pico por obra, como indicadores de sostenibilidad del resultado económico.'),
 18:('El cierre en 2023 en lugar de 2019 costó USD 0,17 millones de valor presente con la regla por componente (cota superior de 48,1 millones); la cifra anterior de 32,1 millones se retira. El 96 % del CAPEX de medición se pagó después de 2019 y su vida útil se agota en 2037.',
 '(Banco y ejecutor) Separar los cronogramas de adquisición del componente tecnológico y de la obra civil, y valorar en cada extensión de plazo el costo de la demora con el método de esta evaluación.'),
 19:('La propuesta de préstamo de 2014 no publicó VAN ni TIR del Programa: no hay contraste ex ante-ex post ni calibración del sesgo de las estimaciones de diseño.',
 '(Banco) Publicar la estimación económica ex ante en la propuesta de préstamo, con sus parámetros y bandas, como referencia obligatoria de la evaluación de cierre.'),
 20:('Tres decisiones exceden el alcance técnico de la evaluación (Análisis Contrafactual, apartado 10.5): la armonización de la valoración de la energía nueva (13,80 US$/MWh) y de la recuperada (92,00); la convención de cumplimiento de FMIk y TTIk; y el factor de utilización de la capacidad nueva (1,00). El personal capacitado se publica como 1.999 (Tabla 1, nota 2).',
 '(Banco) Resolver formalmente las tres decisiones y dejar constancia en el expediente; hasta entonces este informe publica la lectura prudente y declara la alternativa. El PMR vigente muestra 1.607 por su definición del universo; la cifra adoptada en todo el paquete es 1.999.'),
 21:('El 91 % del deterioro nacional de pérdidas entre enero de 2022 y enero de 2023 es no técnico y se concentra en CNEL EP; Santa Elena y Esmeraldas, críticas, no recibieron medidores; cuatro unidades subdeclaran ≈438 GWh/año (≈USD 40 millones anuales a tarifa).',
 '(Banco, CNEL EP y ARCONEL) Dirigir la siguiente fase de medición a Santa Elena, Esmeraldas y los alimentadores críticos (Cuadro 24 del EEO#2), con línea base de consumo por usuario y auditoría de la declaración de pérdidas por etapa funcional.'),
 22:('Los usuarios concentran el valor (excedente y confiabilidad), las distribuidoras ganan porque la facturación recuperada y el ahorro remoto superan su O&M, y el Estado financia USD 77,6 millones de CAPEX con deuda soberana.',
 '(Banco y MEF) Proteger los ingresos de las distribuidoras por medición y gestión remota como condición de sostenibilidad: de ellos depende el O&M que sostiene más de la mitad del valor.'),
 23:('Siete vacíos de dato declarados al cierre, sin nuevas solicitudes a las distribuidoras: conexiones nuevas por obra; holgura SCADA de las subestaciones vecinas; 128 medidores sin línea base; O&M por activo; costos de corte y lectura previos al AMI; pérdidas no técnicas de cuatro unidades de CNEL; y consumo por usuario de las cuentas con medidor del Programa.',
 '(Ejecutor, EED y CNEL EP) Cerrar esos siete vacíos en las operaciones sucesoras, registrando el dato a medida que se entregue cada obra o servicio; cada uno acota un frente abierto declarado en los anexos.')}
for r,(h,rc) in H.items(): cell_set(T,r,0,h,nth=1); cell_set(T,r,1,rc,nth=1)
NEW=[['Regla de transferencias y coherencia entre programas. La regla aplicada a la medición inteligente es la decisión de mayor efecto sobre el VAN (convención de facturación USD 47,73 millones frente a 33,10 publicados) y es coherente con el programa hermano de medición inteligente financiado por el Banco.','(Banco) Mantener la regla de transferencias, y no la convención de facturación, en cualquier evaluación conjunta o comparación entre ambos programas.'],
 ['Tarifas y costos como principal riesgo del signo. El programa puede resultar negativo por precios y no por cantidades: la tarifa cubre el costo marginal de la energía en años normales y deja de cubrirlo en crisis de generación (sección II.3).','(Banco y ejecutor) Seguir la tarifa media y el costo del servicio del regulador como indicadores de riesgo, con los valores de cambio como umbrales (tarifa 3,57 ¢/kWh; utilización 41,66 %; brecha media 0,81 ¢/kWh); valorar la energía adicional neta de su costo de suministro cuando la tarifa no lo cubra; y acompañar las ampliaciones con una senda de suficiencia tarifaria o focalización del subsidio.'],
 ['Transferencias hacia los usuarios de mayor consumo. Mientras la tarifa esté bajo el costo medio del servicio, cada kWh adicional lleva un subsidio implícito a cargo del Estado: USD 88 millones de valor presente con la brecha de año normal y 229 con la de crisis. La medición inteligente redujo una transferencia de unos USD 4,1 millones anuales.','(Banco y ejecutor) Reportar la incidencia distributiva por categoría tarifaria (energía servida y tarifa frente al costo del servicio) y considerar la focalización de los subsidios como condición de la eficiencia asignativa de las inversiones en capacidad.'],
 ['Registro progresivo de datos. Las brechas de atribución nacen de reconstruir al cierre lo que debió registrarse al entregar cada obra o servicio.','(Ejecutor y EED) Archivar al energizar cada obra: contratos nuevos por alimentador; balance mensual de energía de los transformadores con AMI doce meses antes y después; códigos SISDAT de alimentador y subestación; actas de energización; y ventas y pliego por categoría tarifaria en el perímetro de las obras.'],
 ['Línea base antes de invertir. Los canales valorados por contribución (frecuencia, duración, acceso y regularización en distribución) carecen de una línea base de consumo o de calidad levantada antes de la obra.','(Banco) Exigir esa línea base, por alimentador o por usuario, como condición previa al primer desembolso de cada obra y no como reconstrucción ex post.'],
 ['No depender de un solo canal. Los beneficios de confiabilidad explican el 31,2 % del valor presente de los beneficios (41,9 % la continuidad en conjunto) y se valoran por contribución, no por atribución.','(Banco) Diversificar desde el diseño los canales de beneficio monetizable de los programas sucesores, en lugar de descansar en uno o dos cuya identificación causal es solo una contribución.']]
add_rows(T,NEW,nth=1)
for i in (1397,1398,1399,1400,1401,1402): delete_para(i)
print('genéricos:',gen_pass([('la lectura publicada','el resultado publicado'),('lectura publicada','resultado publicado')]))
RES=r'lectura publicada|solicitud|32,1 millones de valor presente sobre|1,94 GWh'
Lc=L.finish('salida_fin/PCR_EC-L1147 (con control de cambios).docx','salida_fin/PCR_EC-L1147.docx',RES,'salida_fin/log_PCR_edit.json')
# palabras después: localizar II.3 e IV en el limpio
def wsec(start,end=None):
    i0=next(i for i,t in enumerate(Lc) if i>300 and t.strip().startswith(start)); i1=next(i for i,t in enumerate(Lc) if i>i0 and t.strip().startswith(end)) if end else len(Lc); return sum(len(t.split()) for t in Lc[i0:i1])
print('palabras II.3 antes',w_ii3_antes,'después',wsec('II.3','II.4')); print('palabras IV antes',w_iv_antes,'después',wsec('IV. Hallazgos'))
